using HealthLink.Api.Entities.Enums;

namespace HealthLink.Api.Dtos.Expert
{
    public class ExpertAvailabilitySlotResponse
    {
        public DateTime StartDateTime { get; set; }
        public DateTime EndDateTime { get; set; }
        public SlotStatus Status { get; set; }
        public bool IsAutoGenerated { get; set; } = false;
    }
}
