CREATE TABLE "DiscountCodes" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Code" character varying(50) NOT NULL,
    "Description" character varying(255),
    "DiscountType" integer NOT NULL,
    "DiscountValue" numeric(18,2) NOT NULL,
    "MaxUsageCount" integer,
    "UsedCount" integer NOT NULL DEFAULT 0,
    "ValidFrom" timestamp with time zone NOT NULL,
    "ValidTo" timestamp with time zone,
    "ApplicableExpertType" integer NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_DiscountCodes" PRIMARY KEY ("Id")
);


CREATE TABLE "ServicePackages" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(150) NOT NULL,
    "Description" text,
    "ExpertType" integer NOT NULL,
    "SessionCount" integer NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "Currency" character varying(10) NOT NULL DEFAULT 'TRY',
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_ServicePackages" PRIMARY KEY ("Id")
);


CREATE TABLE "Specializations" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(256) NOT NULL,
    "Description" text,
    "ExpertType" integer NOT NULL,
    "Category" integer NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Specializations" PRIMARY KEY ("Id")
);


CREATE TABLE "SystemSettings" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Key" character varying(200) NOT NULL,
    "Value" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_SystemSettings" PRIMARY KEY ("Id")
);


CREATE TABLE "Users" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Email" character varying(256) NOT NULL,
    "PasswordHash" text NOT NULL,
    "PasswordSalt" text NOT NULL,
    "Phone" character varying(32),
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);


CREATE TABLE "Admins" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "IsSystemAdmin" boolean NOT NULL DEFAULT FALSE,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Admins" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Admins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "AuditLogs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint,
    "ActionType" character varying(100) NOT NULL,
    "TargetType" character varying(100),
    "TargetId" bigint,
    "IpAddress" character varying(50),
    "MetaJson" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AuditLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE SET NULL
);


CREATE TABLE "Clients" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "FirstName" character varying(100) NOT NULL,
    "LastName" character varying(100) NOT NULL,
    "Gender" integer,
    "BirthDate" timestamp with time zone,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Clients" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Clients_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "ContentItems" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "SubTitle" character varying(300),
    "Slug" character varying(200) NOT NULL,
    "Type" integer NOT NULL,
    "Category" character varying(100),
    "CoverImageUrl" character varying(500),
    "BodyHtml" text NOT NULL,
    "SeoTitle" character varying(200),
    "SeoDescription" character varying(300),
    "Status" integer NOT NULL,
    "AuthorUserId" bigint NOT NULL,
    "PublishedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "ViewCount" integer NOT NULL,
    "LikeCount" integer NOT NULL,
    "DislikeCount" integer NOT NULL,
    CONSTRAINT "PK_ContentItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ContentItems_Users_AuthorUserId" FOREIGN KEY ("AuthorUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "Experts" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "ExpertType" integer NOT NULL,
    "Status" integer NOT NULL,
    "DisplayName" character varying(150),
    "Bio" character varying(2000),
    "ProfilePhotoUrl" text,
    "IntroVideoUrl" text,
    "City" character varying(100),
    "WorkType" integer,
    "ExperienceStartDate" date,
    "AverageRating" numeric(3,2),
    "TotalReviewCount" integer NOT NULL DEFAULT 0,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Experts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Experts_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "ClientPackages" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ClientId" bigint NOT NULL,
    "ServicePackageId" bigint NOT NULL,
    "TotalSessions" integer NOT NULL,
    "UsedSessions" integer NOT NULL DEFAULT 0,
    "Status" integer NOT NULL,
    "PurchaseDate" timestamp with time zone NOT NULL,
    "ExpireDate" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_ClientPackages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ClientPackages_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ClientPackages_ServicePackages_ServicePackageId" FOREIGN KEY ("ServicePackageId") REFERENCES "ServicePackages" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "ContentItemReactions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ContentItemId" bigint NOT NULL,
    "UserId" bigint NOT NULL,
    "IsLike" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ContentItemReactions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ContentItemReactions_ContentItems_ContentItemId" FOREIGN KEY ("ContentItemId") REFERENCES "ContentItems" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ContentItemReactions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Conversations" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ClientId" bigint NOT NULL,
    "ExpertId" bigint NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "LastMessageAt" timestamp with time zone,
    "IsFrozen" boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_Conversations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Conversations_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Conversations_Experts_ExpertId" FOREIGN KEY ("ExpertId") REFERENCES "Experts" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "ExpertCertificates" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ExpertId" bigint NOT NULL,
    "Name" text NOT NULL,
    "Issuer" text,
    "Year" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ExpertCertificates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ExpertCertificates_Experts_ExpertId" FOREIGN KEY ("ExpertId") REFERENCES "Experts" ("Id") ON DELETE CASCADE
);


CREATE TABLE "ExpertScheduleExceptions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ExpertId" bigint NOT NULL,
    "Date" date NOT NULL,
    "Type" integer NOT NULL,
    "StartTime" time without time zone,
    "EndTime" time without time zone,
    "Reason" character varying(250),
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ExpertScheduleExceptions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ExpertScheduleExceptions_Experts_ExpertId" FOREIGN KEY ("ExpertId") REFERENCES "Experts" ("Id") ON DELETE CASCADE
);


CREATE TABLE "ExpertScheduleTemplates" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ExpertId" bigint NOT NULL,
    "DayOfWeek" integer NOT NULL,
    "IsOpen" boolean NOT NULL,
    "WorkStartTime" time without time zone,
    "WorkEndTime" time without time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_ExpertScheduleTemplates" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ExpertScheduleTemplates_Experts_ExpertId" FOREIGN KEY ("ExpertId") REFERENCES "Experts" ("Id") ON DELETE CASCADE
);


CREATE TABLE "ExpertSpecializations" (
    "ExpertId" bigint NOT NULL,
    "SpecializationId" bigint NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ExpertSpecializations" PRIMARY KEY ("ExpertId", "SpecializationId"),
    CONSTRAINT "FK_ExpertSpecializations_Experts_ExpertId" FOREIGN KEY ("ExpertId") REFERENCES "Experts" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ExpertSpecializations_Specializations_SpecializationId" FOREIGN KEY ("SpecializationId") REFERENCES "Specializations" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "Appointments" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ClientId" bigint NOT NULL,
    "ExpertId" bigint NOT NULL,
    "ClientPackageId" bigint,
    "ServiceType" integer NOT NULL,
    "StartDateTime" timestamp with time zone NOT NULL,
    "EndDateTime" timestamp with time zone NOT NULL,
    "ZoomLink" character varying(500),
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Appointments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Appointments_ClientPackages_ClientPackageId" FOREIGN KEY ("ClientPackageId") REFERENCES "ClientPackages" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Appointments_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Appointments_Experts_ExpertId" FOREIGN KEY ("ExpertId") REFERENCES "Experts" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "Payments" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ClientId" bigint NOT NULL,
    "ClientPackageId" bigint NOT NULL,
    "Amount" numeric(18,2) NOT NULL,
    "Currency" character varying(10) NOT NULL DEFAULT 'TRY',
    "PaymentMethod" character varying(50) NOT NULL,
    "Status" integer NOT NULL,
    "Gateway" integer NOT NULL,
    "GatewayPaymentId" character varying(100),
    "ProviderRawResponse" text,
    "ConfirmedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Payments_ClientPackages_ClientPackageId" FOREIGN KEY ("ClientPackageId") REFERENCES "ClientPackages" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Payments_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "ConversationFlags" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ConversationId" bigint NOT NULL,
    "ReportedByUserId" bigint NOT NULL,
    "Reason" character varying(250) NOT NULL,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_ConversationFlags" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ConversationFlags_Conversations_ConversationId" FOREIGN KEY ("ConversationId") REFERENCES "Conversations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ConversationFlags_Users_ReportedByUserId" FOREIGN KEY ("ReportedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "Messages" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ConversationId" bigint NOT NULL,
    "SenderUserId" bigint NOT NULL,
    "MessageText" character varying(1000) NOT NULL,
    "IsRead" boolean NOT NULL DEFAULT FALSE,
    "ReadAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Messages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Messages_Conversations_ConversationId" FOREIGN KEY ("ConversationId") REFERENCES "Conversations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Messages_Users_SenderUserId" FOREIGN KEY ("SenderUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "AppointmentNotes" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AppointmentId" bigint NOT NULL,
    "ClientId" bigint NOT NULL,
    "NoteText" character varying(1000) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_AppointmentNotes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AppointmentNotes_Appointments_AppointmentId" FOREIGN KEY ("AppointmentId") REFERENCES "Appointments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AppointmentNotes_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "AppointmentReports" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AppointmentId" bigint NOT NULL,
    "ExpertId" bigint NOT NULL,
    "ReportText" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_AppointmentReports" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AppointmentReports_Appointments_AppointmentId" FOREIGN KEY ("AppointmentId") REFERENCES "Appointments" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AppointmentReports_Experts_ExpertId" FOREIGN KEY ("ExpertId") REFERENCES "Experts" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "Complaints" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ClientId" bigint,
    "ExpertId" bigint,
    "AppointmentId" bigint,
    "Category" integer NOT NULL,
    "Type" integer NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Description" text,
    "Status" integer NOT NULL,
    "AdminNote" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "ClosedAt" timestamp with time zone,
    CONSTRAINT "PK_Complaints" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Complaints_Appointments_AppointmentId" FOREIGN KEY ("AppointmentId") REFERENCES "Appointments" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Complaints_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Complaints_Experts_ExpertId" FOREIGN KEY ("ExpertId") REFERENCES "Experts" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "Reviews" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AppointmentId" bigint NOT NULL,
    "ClientId" bigint NOT NULL,
    "ExpertId" bigint NOT NULL,
    "Rating" integer NOT NULL,
    "Comment" character varying(500),
    "Status" integer NOT NULL,
    "AdminNote" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL,
    "ReviewedAt" timestamp with time zone,
    "ReviewedByAdminId" bigint,
    CONSTRAINT "PK_Reviews" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Reviews_Appointments_AppointmentId" FOREIGN KEY ("AppointmentId") REFERENCES "Appointments" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Reviews_Clients_ClientId" FOREIGN KEY ("ClientId") REFERENCES "Clients" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Reviews_Experts_ExpertId" FOREIGN KEY ("ExpertId") REFERENCES "Experts" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Reviews_Users_ReviewedByAdminId" FOREIGN KEY ("ReviewedByAdminId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "PaymentDiscountUsages" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "PaymentId" bigint NOT NULL,
    "DiscountCodeId" bigint NOT NULL,
    "AppliedAmount" numeric(18,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_PaymentDiscountUsages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PaymentDiscountUsages_DiscountCodes_DiscountCodeId" FOREIGN KEY ("DiscountCodeId") REFERENCES "DiscountCodes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_PaymentDiscountUsages_Payments_PaymentId" FOREIGN KEY ("PaymentId") REFERENCES "Payments" ("Id") ON DELETE RESTRICT
);


INSERT INTO "ServicePackages" ("Id", "CreatedAt", "Currency", "Description", "ExpertType", "IsActive", "Name", "Price", "SessionCount", "UpdatedAt")
VALUES (1, TIMESTAMPTZ '2026-02-04T13:49:40.159994Z', 'TRY', 'One online consultation session', 0, TRUE, 'Single Session', 750.0, 1, NULL);
INSERT INTO "ServicePackages" ("Id", "CreatedAt", "Currency", "Description", "ExpertType", "IsActive", "Name", "Price", "SessionCount", "UpdatedAt")
VALUES (2, TIMESTAMPTZ '2026-02-04T13:49:40.159994Z', 'TRY', 'Four online consultation sessions', 0, TRUE, '4 Session Package', 2600.0, 4, NULL);


INSERT INTO "Specializations" ("Id", "Category", "CreatedAt", "Description", "ExpertType", "IsActive", "Name", "UpdatedAt")
VALUES (1, 0, TIMESTAMPTZ '2026-02-04T13:49:40.159988Z', NULL, 0, TRUE, 'Clinical Nutrition', NULL);
INSERT INTO "Specializations" ("Id", "Category", "CreatedAt", "Description", "ExpertType", "IsActive", "Name", "UpdatedAt")
VALUES (2, 0, TIMESTAMPTZ '2026-02-04T13:49:40.159989Z', NULL, 0, TRUE, 'Sports Nutrition', NULL);
INSERT INTO "Specializations" ("Id", "Category", "CreatedAt", "Description", "ExpertType", "IsActive", "Name", "UpdatedAt")
VALUES (3, 0, TIMESTAMPTZ '2026-02-04T13:49:40.159989Z', NULL, 0, TRUE, 'Weight Management', NULL);


INSERT INTO "SystemSettings" ("Id", "CreatedAt", "Key", "UpdatedAt", "Value")
VALUES (1, TIMESTAMPTZ '2026-02-04T13:49:40.159964Z', 'Platform.CommissionRate', NULL, '0.15');
INSERT INTO "SystemSettings" ("Id", "CreatedAt", "Key", "UpdatedAt", "Value")
VALUES (2, TIMESTAMPTZ '2026-02-04T13:49:40.159965Z', 'Session.DefaultDurationMinutes', NULL, '30');
INSERT INTO "SystemSettings" ("Id", "CreatedAt", "Key", "UpdatedAt", "Value")
VALUES (3, TIMESTAMPTZ '2026-02-04T13:49:40.159965Z', 'Session.CancelLimitHours', NULL, '24');


CREATE UNIQUE INDEX "IX_Admins_UserId" ON "Admins" ("UserId");


CREATE INDEX "IX_AppointmentNotes_AppointmentId" ON "AppointmentNotes" ("AppointmentId");


CREATE INDEX "IX_AppointmentNotes_ClientId" ON "AppointmentNotes" ("ClientId");


CREATE INDEX "IX_AppointmentReports_AppointmentId" ON "AppointmentReports" ("AppointmentId");


CREATE INDEX "IX_AppointmentReports_ExpertId" ON "AppointmentReports" ("ExpertId");


CREATE INDEX "IX_Appointments_ClientId" ON "Appointments" ("ClientId");


CREATE INDEX "IX_Appointments_ClientPackageId" ON "Appointments" ("ClientPackageId");


CREATE INDEX "IX_Appointments_ExpertId" ON "Appointments" ("ExpertId");


CREATE INDEX "IX_AuditLogs_UserId" ON "AuditLogs" ("UserId");


CREATE INDEX "IX_ClientPackages_ClientId" ON "ClientPackages" ("ClientId");


CREATE INDEX "IX_ClientPackages_ServicePackageId" ON "ClientPackages" ("ServicePackageId");


CREATE UNIQUE INDEX "IX_Clients_UserId" ON "Clients" ("UserId");


CREATE INDEX "IX_Complaints_AppointmentId" ON "Complaints" ("AppointmentId");


CREATE INDEX "IX_Complaints_ClientId" ON "Complaints" ("ClientId");


CREATE INDEX "IX_Complaints_ExpertId" ON "Complaints" ("ExpertId");


CREATE INDEX "IX_ContentItemReactions_ContentItemId" ON "ContentItemReactions" ("ContentItemId");


CREATE INDEX "IX_ContentItemReactions_UserId" ON "ContentItemReactions" ("UserId");


CREATE INDEX "IX_ContentItems_AuthorUserId" ON "ContentItems" ("AuthorUserId");


CREATE UNIQUE INDEX "IX_ContentItems_Slug" ON "ContentItems" ("Slug");


CREATE INDEX "IX_ConversationFlags_ConversationId" ON "ConversationFlags" ("ConversationId");


CREATE INDEX "IX_ConversationFlags_ReportedByUserId" ON "ConversationFlags" ("ReportedByUserId");


CREATE UNIQUE INDEX "IX_Conversations_ClientId_ExpertId" ON "Conversations" ("ClientId", "ExpertId");


CREATE INDEX "IX_Conversations_ExpertId" ON "Conversations" ("ExpertId");


CREATE UNIQUE INDEX "IX_DiscountCodes_Code" ON "DiscountCodes" ("Code");


CREATE INDEX "IX_ExpertCertificates_ExpertId" ON "ExpertCertificates" ("ExpertId");


CREATE UNIQUE INDEX "IX_Experts_UserId" ON "Experts" ("UserId");


CREATE INDEX "IX_ExpertScheduleExceptions_ExpertId" ON "ExpertScheduleExceptions" ("ExpertId");


CREATE UNIQUE INDEX "IX_ExpertScheduleTemplates_ExpertId_DayOfWeek" ON "ExpertScheduleTemplates" ("ExpertId", "DayOfWeek");


CREATE INDEX "IX_ExpertSpecializations_SpecializationId" ON "ExpertSpecializations" ("SpecializationId");


CREATE INDEX "IX_Messages_ConversationId" ON "Messages" ("ConversationId");


CREATE INDEX "IX_Messages_SenderUserId" ON "Messages" ("SenderUserId");


CREATE INDEX "IX_PaymentDiscountUsages_DiscountCodeId" ON "PaymentDiscountUsages" ("DiscountCodeId");


CREATE INDEX "IX_PaymentDiscountUsages_PaymentId" ON "PaymentDiscountUsages" ("PaymentId");


CREATE INDEX "IX_Payments_ClientId" ON "Payments" ("ClientId");


CREATE UNIQUE INDEX "IX_Payments_ClientPackageId" ON "Payments" ("ClientPackageId");


CREATE UNIQUE INDEX "IX_Reviews_AppointmentId" ON "Reviews" ("AppointmentId");


CREATE INDEX "IX_Reviews_ClientId" ON "Reviews" ("ClientId");


CREATE INDEX "IX_Reviews_ExpertId" ON "Reviews" ("ExpertId");


CREATE INDEX "IX_Reviews_ReviewedByAdminId" ON "Reviews" ("ReviewedByAdminId");


CREATE UNIQUE INDEX "IX_Specializations_Name" ON "Specializations" ("Name");


CREATE UNIQUE INDEX "IX_SystemSettings_Key" ON "SystemSettings" ("Key");


CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");


SELECT setval(
    pg_get_serial_sequence('"ServicePackages"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "ServicePackages") + 1,
        nextval(pg_get_serial_sequence('"ServicePackages"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Specializations"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Specializations") + 1,
        nextval(pg_get_serial_sequence('"Specializations"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"SystemSettings"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "SystemSettings") + 1,
        nextval(pg_get_serial_sequence('"SystemSettings"', 'Id'))),
    false);


