// <auto-generated />
using System;
using HealthLink.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HealthLink.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260217124708_AddIyzicoTokenToPayment")]
    partial class AddIyzicoTokenToPayment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HealthLink.Api.Entities.Admin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsSystemAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("HealthLink.Api.Entities.Appointment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ClientPackageId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DailyRoomName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExpertId")
                        .HasColumnType("bigint");

                    b.Property<string>("MeetingUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RecordingStatus")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("RecordingUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ServiceType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasMaxLength(30)
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientPackageId");

                    b.HasIndex("ExpertId");

                    b.ToTable("Appointments", (string)null);
                });

            modelBuilder.Entity("HealthLink.Api.Entities.AppointmentNote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AppointmentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ClientId");

                    b.ToTable("AppointmentNotes", (string)null);
                });

            modelBuilder.Entity("HealthLink.Api.Entities.AppointmentReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AppointmentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExpertId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReportText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ExpertId");

                    b.ToTable("AppointmentReports", (string)null);
                });

            modelBuilder.Entity("HealthLink.Api.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MetaJson")
                        .HasColumnType("text");

                    b.Property<long?>("TargetId")
                        .HasColumnType("bigint");

                    b.Property<string>("TargetType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("HealthLink.Api.Entities.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Gender")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("HealthLink.Api.Entities.ClientPackage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ServicePackageId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TotalSessions")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsedSessions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ServicePackageId");

                    b.ToTable("ClientPackages", (string)null);
                });

            modelBuilder.Entity("HealthLink.Api.Entities.Complaint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AdminNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long?>("AppointmentId")
                        .HasColumnType("bigint");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<long?>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long?>("ExpertId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ClientId");

                    b.HasIndex("ExpertId");

                    b.ToTable("Complaints", (string)null);
                });

            modelBuilder.Entity("HealthLink.Api.Entities.ContentItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("BodyHtml")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DislikeCount")
                        .HasColumnType("integer");

                    b.Property<int>("LikeCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SeoDescription")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("SeoTitle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SubTitle")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ContentItems", (string)null);
                });

            modelBuilder.Entity("HealthLink.Api.Entities.ContentItemReaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ContentItemId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsLike")
                        .HasColumnType("boolean");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ContentItemId");

                    b.HasIndex("UserId");

                    b.ToTable("ContentItemReactions");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.Conversation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExpertId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsFrozen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId");

                    b.HasIndex("ClientId", "ExpertId")
                        .IsUnique();

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("HealthLink.Api.Entities.ConversationFlag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<long>("ReportedByUserId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("ReportedByUserId");

                    b.ToTable("ConversationFlags", (string)null);
                });

            modelBuilder.Entity("HealthLink.Api.Entities.DiscountCode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ApplicableExpertType")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("DiscountType")
                        .HasColumnType("integer");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("MaxUsageCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UsedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DiscountCodes", (string)null);
                });

            modelBuilder.Entity("HealthLink.Api.Entities.Expert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateOnly?>("ExperienceStartDate")
                        .HasColumnType("date");

                    b.Property<int>("ExpertType")
                        .HasColumnType("integer");

                    b.Property<string>("IntroVideoUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ProfileDescription")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TotalReviewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<int?>("WorkType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Experts", (string)null);
                });

            modelBuilder.Entity("HealthLink.Api.Entities.ExpertAvailabilitySlot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<long>("ExpertId")
                        .HasColumnType("bigint");

                    b.Property<string>("SlotTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TimeSlotTemplateId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TimeSlotTemplateId");

                    b.HasIndex("ExpertId", "Date", "TimeSlotTemplateId")
                        .IsUnique();

                    b.ToTable("ExpertAvailabilitySlots", (string)null);
                });

            modelBuilder.Entity("HealthLink.Api.Entities.ExpertCertificate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExpertId")
                        .HasColumnType("bigint");

                    b.Property<string>("Issuer")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId");

                    b.ToTable("ExpertCertificates");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.ExpertScheduleException", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<long>("ExpertId")
                        .HasColumnType("bigint");

                    b.Property<string>("Reason")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("Type")
                        .HasMaxLength(20)
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId");

                    b.ToTable("ExpertScheduleExceptions", (string)null);
                });

            modelBuilder.Entity("HealthLink.Api.Entities.ExpertScheduleTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("AutoMarkAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<long>("ExpertId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("ExpertScheduleTemplates", (string)null);
                });

            modelBuilder.Entity("HealthLink.Api.Entities.ExpertScheduleTimeSlot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("ExpertScheduleTimeSlots", (string)null);
                });

            modelBuilder.Entity("HealthLink.Api.Entities.ExpertSpecialization", b =>
                {
                    b.Property<long>("ExpertId")
                        .HasColumnType("bigint");

                    b.Property<long>("SpecializationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ExpertId", "SpecializationId");

                    b.HasIndex("SpecializationId");

                    b.ToTable("ExpertSpecializations", (string)null);
                });

            modelBuilder.Entity("HealthLink.Api.Entities.FavoriteExpert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExpertId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ExpertId");

                    b.HasIndex("ClientId", "ExpertId")
                        .IsUnique();

                    b.ToTable("FavoriteExperts", (string)null);
                });

            modelBuilder.Entity("HealthLink.Api.Entities.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("SenderUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("Messages", (string)null);
                });

            modelBuilder.Entity("HealthLink.Api.Entities.Payment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClientPackageId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("TRY");

                    b.Property<int>("Gateway")
                        .HasColumnType("integer");

                    b.Property<string>("GatewayPaymentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IyzicoToken")
                        .HasColumnType("text");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderRawResponse")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientPackageId")
                        .IsUnique();

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("HealthLink.Api.Entities.PaymentDiscountUsage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal>("AppliedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DiscountCodeId")
                        .HasColumnType("bigint");

                    b.Property<long>("PaymentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DiscountCodeId");

                    b.HasIndex("PaymentId");

                    b.ToTable("PaymentDiscountUsages", (string)null);
                });

            modelBuilder.Entity("HealthLink.Api.Entities.Review", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AdminNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("AppointmentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ClientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExpertId")
                        .HasColumnType("bigint");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("ReviewedByAdminId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("ClientId");

                    b.HasIndex("ExpertId");

                    b.HasIndex("ReviewedByAdminId");

                    b.ToTable("Reviews", (string)null);
                });

            modelBuilder.Entity("HealthLink.Api.Entities.ServicePackage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("TRY");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ExpertType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("SessionCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ValidityDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ServicePackages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 2, 17, 12, 47, 8, 2, DateTimeKind.Utc).AddTicks(881),
                            Currency = "TRY",
                            Description = "One online consultation session",
                            ExpertType = 0,
                            IsActive = true,
                            Name = "Single Session",
                            Price = 750m,
                            SessionCount = 1,
                            ValidityDays = 30
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 2, 17, 12, 47, 8, 2, DateTimeKind.Utc).AddTicks(884),
                            Currency = "TRY",
                            Description = "Four online consultation sessions",
                            ExpertType = 0,
                            IsActive = true,
                            Name = "4 Session Package",
                            Price = 2600m,
                            SessionCount = 4,
                            ValidityDays = 90
                        });
                });

            modelBuilder.Entity("HealthLink.Api.Entities.Specialization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ExpertType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Specializations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = 0,
                            CreatedAt = new DateTime(2026, 2, 17, 12, 47, 8, 2, DateTimeKind.Utc).AddTicks(839),
                            ExpertType = 0,
                            IsActive = true,
                            Name = "Clinical Nutrition"
                        },
                        new
                        {
                            Id = 2L,
                            Category = 0,
                            CreatedAt = new DateTime(2026, 2, 17, 12, 47, 8, 2, DateTimeKind.Utc).AddTicks(841),
                            ExpertType = 0,
                            IsActive = true,
                            Name = "Sports Nutrition"
                        },
                        new
                        {
                            Id = 3L,
                            Category = 0,
                            CreatedAt = new DateTime(2026, 2, 17, 12, 47, 8, 2, DateTimeKind.Utc).AddTicks(843),
                            ExpertType = 0,
                            IsActive = true,
                            Name = "Weight Management"
                        });
                });

            modelBuilder.Entity("HealthLink.Api.Entities.SystemSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SystemSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 2, 17, 12, 47, 8, 2, DateTimeKind.Utc).AddTicks(682),
                            Key = "Platform.CommissionRate",
                            Value = "0.15"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 2, 17, 12, 47, 8, 2, DateTimeKind.Utc).AddTicks(685),
                            Key = "Session.DefaultDurationMinutes",
                            Value = "30"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2026, 2, 17, 12, 47, 8, 2, DateTimeKind.Utc).AddTicks(689),
                            Key = "Session.CancelLimitHours",
                            Value = "24"
                        });
                });

            modelBuilder.Entity("HealthLink.Api.Entities.TimeSlotTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.ToTable("TimeSlotTemplates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(0, 30, 0),
                            SortOrder = 1,
                            StartTime = new TimeOnly(0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(1, 0, 0),
                            SortOrder = 2,
                            StartTime = new TimeOnly(0, 30, 0)
                        },
                        new
                        {
                            Id = 3,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(1, 30, 0),
                            SortOrder = 3,
                            StartTime = new TimeOnly(1, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(2, 0, 0),
                            SortOrder = 4,
                            StartTime = new TimeOnly(1, 30, 0)
                        },
                        new
                        {
                            Id = 5,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(2, 30, 0),
                            SortOrder = 5,
                            StartTime = new TimeOnly(2, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(3, 0, 0),
                            SortOrder = 6,
                            StartTime = new TimeOnly(2, 30, 0)
                        },
                        new
                        {
                            Id = 7,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(3, 30, 0),
                            SortOrder = 7,
                            StartTime = new TimeOnly(3, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(4, 0, 0),
                            SortOrder = 8,
                            StartTime = new TimeOnly(3, 30, 0)
                        },
                        new
                        {
                            Id = 9,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(4, 30, 0),
                            SortOrder = 9,
                            StartTime = new TimeOnly(4, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(5, 0, 0),
                            SortOrder = 10,
                            StartTime = new TimeOnly(4, 30, 0)
                        },
                        new
                        {
                            Id = 11,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(5, 30, 0),
                            SortOrder = 11,
                            StartTime = new TimeOnly(5, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(6, 0, 0),
                            SortOrder = 12,
                            StartTime = new TimeOnly(5, 30, 0)
                        },
                        new
                        {
                            Id = 13,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(6, 30, 0),
                            SortOrder = 13,
                            StartTime = new TimeOnly(6, 0, 0)
                        },
                        new
                        {
                            Id = 14,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(7, 0, 0),
                            SortOrder = 14,
                            StartTime = new TimeOnly(6, 30, 0)
                        },
                        new
                        {
                            Id = 15,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(7, 30, 0),
                            SortOrder = 15,
                            StartTime = new TimeOnly(7, 0, 0)
                        },
                        new
                        {
                            Id = 16,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(8, 0, 0),
                            SortOrder = 16,
                            StartTime = new TimeOnly(7, 30, 0)
                        },
                        new
                        {
                            Id = 17,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(8, 30, 0),
                            SortOrder = 17,
                            StartTime = new TimeOnly(8, 0, 0)
                        },
                        new
                        {
                            Id = 18,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(9, 0, 0),
                            SortOrder = 18,
                            StartTime = new TimeOnly(8, 30, 0)
                        },
                        new
                        {
                            Id = 19,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(9, 30, 0),
                            SortOrder = 19,
                            StartTime = new TimeOnly(9, 0, 0)
                        },
                        new
                        {
                            Id = 20,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(10, 0, 0),
                            SortOrder = 20,
                            StartTime = new TimeOnly(9, 30, 0)
                        },
                        new
                        {
                            Id = 21,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(10, 30, 0),
                            SortOrder = 21,
                            StartTime = new TimeOnly(10, 0, 0)
                        },
                        new
                        {
                            Id = 22,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(11, 0, 0),
                            SortOrder = 22,
                            StartTime = new TimeOnly(10, 30, 0)
                        },
                        new
                        {
                            Id = 23,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(11, 30, 0),
                            SortOrder = 23,
                            StartTime = new TimeOnly(11, 0, 0)
                        },
                        new
                        {
                            Id = 24,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(12, 0, 0),
                            SortOrder = 24,
                            StartTime = new TimeOnly(11, 30, 0)
                        },
                        new
                        {
                            Id = 25,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(12, 30, 0),
                            SortOrder = 25,
                            StartTime = new TimeOnly(12, 0, 0)
                        },
                        new
                        {
                            Id = 26,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(13, 0, 0),
                            SortOrder = 26,
                            StartTime = new TimeOnly(12, 30, 0)
                        },
                        new
                        {
                            Id = 27,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(13, 30, 0),
                            SortOrder = 27,
                            StartTime = new TimeOnly(13, 0, 0)
                        },
                        new
                        {
                            Id = 28,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(14, 0, 0),
                            SortOrder = 28,
                            StartTime = new TimeOnly(13, 30, 0)
                        },
                        new
                        {
                            Id = 29,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(14, 30, 0),
                            SortOrder = 29,
                            StartTime = new TimeOnly(14, 0, 0)
                        },
                        new
                        {
                            Id = 30,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(15, 0, 0),
                            SortOrder = 30,
                            StartTime = new TimeOnly(14, 30, 0)
                        },
                        new
                        {
                            Id = 31,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(15, 30, 0),
                            SortOrder = 31,
                            StartTime = new TimeOnly(15, 0, 0)
                        },
                        new
                        {
                            Id = 32,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(16, 0, 0),
                            SortOrder = 32,
                            StartTime = new TimeOnly(15, 30, 0)
                        },
                        new
                        {
                            Id = 33,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(16, 30, 0),
                            SortOrder = 33,
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            Id = 34,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(17, 0, 0),
                            SortOrder = 34,
                            StartTime = new TimeOnly(16, 30, 0)
                        },
                        new
                        {
                            Id = 35,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(17, 30, 0),
                            SortOrder = 35,
                            StartTime = new TimeOnly(17, 0, 0)
                        },
                        new
                        {
                            Id = 36,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(18, 0, 0),
                            SortOrder = 36,
                            StartTime = new TimeOnly(17, 30, 0)
                        },
                        new
                        {
                            Id = 37,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(18, 30, 0),
                            SortOrder = 37,
                            StartTime = new TimeOnly(18, 0, 0)
                        },
                        new
                        {
                            Id = 38,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(19, 0, 0),
                            SortOrder = 38,
                            StartTime = new TimeOnly(18, 30, 0)
                        },
                        new
                        {
                            Id = 39,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(19, 30, 0),
                            SortOrder = 39,
                            StartTime = new TimeOnly(19, 0, 0)
                        },
                        new
                        {
                            Id = 40,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(20, 0, 0),
                            SortOrder = 40,
                            StartTime = new TimeOnly(19, 30, 0)
                        },
                        new
                        {
                            Id = 41,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(20, 30, 0),
                            SortOrder = 41,
                            StartTime = new TimeOnly(20, 0, 0)
                        },
                        new
                        {
                            Id = 42,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(21, 0, 0),
                            SortOrder = 42,
                            StartTime = new TimeOnly(20, 30, 0)
                        },
                        new
                        {
                            Id = 43,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(21, 30, 0),
                            SortOrder = 43,
                            StartTime = new TimeOnly(21, 0, 0)
                        },
                        new
                        {
                            Id = 44,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(22, 0, 0),
                            SortOrder = 44,
                            StartTime = new TimeOnly(21, 30, 0)
                        },
                        new
                        {
                            Id = 45,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(22, 30, 0),
                            SortOrder = 45,
                            StartTime = new TimeOnly(22, 0, 0)
                        },
                        new
                        {
                            Id = 46,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(23, 0, 0),
                            SortOrder = 46,
                            StartTime = new TimeOnly(22, 30, 0)
                        },
                        new
                        {
                            Id = 47,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(23, 30, 0),
                            SortOrder = 47,
                            StartTime = new TimeOnly(23, 0, 0)
                        },
                        new
                        {
                            Id = 48,
                            DurationMinutes = 30,
                            EndTime = new TimeOnly(0, 0, 0),
                            SortOrder = 48,
                            StartTime = new TimeOnly(23, 30, 0)
                        });
                });

            modelBuilder.Entity("HealthLink.Api.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("HealthLink.Api.Entities.Admin", b =>
                {
                    b.HasOne("HealthLink.Api.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("HealthLink.Api.Entities.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.Appointment", b =>
                {
                    b.HasOne("HealthLink.Api.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthLink.Api.Entities.ClientPackage", "ClientPackage")
                        .WithMany()
                        .HasForeignKey("ClientPackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HealthLink.Api.Entities.Expert", "Expert")
                        .WithMany()
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ClientPackage");

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.AppointmentNote", b =>
                {
                    b.HasOne("HealthLink.Api.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthLink.Api.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.AppointmentReport", b =>
                {
                    b.HasOne("HealthLink.Api.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthLink.Api.Entities.Expert", "Expert")
                        .WithMany()
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.AuditLog", b =>
                {
                    b.HasOne("HealthLink.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.Client", b =>
                {
                    b.HasOne("HealthLink.Api.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("HealthLink.Api.Entities.Client", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.ClientPackage", b =>
                {
                    b.HasOne("HealthLink.Api.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthLink.Api.Entities.ServicePackage", "ServicePackage")
                        .WithMany("ClientPackages")
                        .HasForeignKey("ServicePackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ServicePackage");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.Complaint", b =>
                {
                    b.HasOne("HealthLink.Api.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthLink.Api.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HealthLink.Api.Entities.Expert", "Expert")
                        .WithMany()
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Appointment");

                    b.Navigation("Client");

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.ContentItem", b =>
                {
                    b.HasOne("HealthLink.Api.Entities.User", "AuthorUser")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthorUser");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.ContentItemReaction", b =>
                {
                    b.HasOne("HealthLink.Api.Entities.ContentItem", "ContentItem")
                        .WithMany()
                        .HasForeignKey("ContentItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthLink.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.Conversation", b =>
                {
                    b.HasOne("HealthLink.Api.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthLink.Api.Entities.Expert", "Expert")
                        .WithMany()
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.ConversationFlag", b =>
                {
                    b.HasOne("HealthLink.Api.Entities.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthLink.Api.Entities.User", "ReportedByUser")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("ReportedByUser");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.Expert", b =>
                {
                    b.HasOne("HealthLink.Api.Entities.User", "User")
                        .WithOne()
                        .HasForeignKey("HealthLink.Api.Entities.Expert", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.ExpertAvailabilitySlot", b =>
                {
                    b.HasOne("HealthLink.Api.Entities.Expert", "Expert")
                        .WithMany()
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthLink.Api.Entities.TimeSlotTemplate", "TimeSlotTemplate")
                        .WithMany()
                        .HasForeignKey("TimeSlotTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("TimeSlotTemplate");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.ExpertCertificate", b =>
                {
                    b.HasOne("HealthLink.Api.Entities.Expert", "Expert")
                        .WithMany("ExpertCertificates")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.ExpertScheduleException", b =>
                {
                    b.HasOne("HealthLink.Api.Entities.Expert", "Expert")
                        .WithMany()
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.ExpertScheduleTemplate", b =>
                {
                    b.HasOne("HealthLink.Api.Entities.Expert", "Expert")
                        .WithMany()
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.ExpertScheduleTimeSlot", b =>
                {
                    b.HasOne("HealthLink.Api.Entities.ExpertScheduleTemplate", "Template")
                        .WithMany("TimeSlots")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.ExpertSpecialization", b =>
                {
                    b.HasOne("HealthLink.Api.Entities.Expert", "Expert")
                        .WithMany("ExpertSpecializations")
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthLink.Api.Entities.Specialization", "Specialization")
                        .WithMany("ExpertSpecializations")
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Expert");

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.FavoriteExpert", b =>
                {
                    b.HasOne("HealthLink.Api.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthLink.Api.Entities.Expert", "Expert")
                        .WithMany()
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Expert");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.Message", b =>
                {
                    b.HasOne("HealthLink.Api.Entities.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealthLink.Api.Entities.User", "SenderUser")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.Payment", b =>
                {
                    b.HasOne("HealthLink.Api.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthLink.Api.Entities.ClientPackage", "ClientPackage")
                        .WithOne()
                        .HasForeignKey("HealthLink.Api.Entities.Payment", "ClientPackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ClientPackage");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.PaymentDiscountUsage", b =>
                {
                    b.HasOne("HealthLink.Api.Entities.DiscountCode", "DiscountCode")
                        .WithMany()
                        .HasForeignKey("DiscountCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthLink.Api.Entities.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DiscountCode");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.Review", b =>
                {
                    b.HasOne("HealthLink.Api.Entities.Appointment", "Appointment")
                        .WithOne()
                        .HasForeignKey("HealthLink.Api.Entities.Review", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthLink.Api.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthLink.Api.Entities.Expert", "Expert")
                        .WithMany()
                        .HasForeignKey("ExpertId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HealthLink.Api.Entities.User", "ReviewedByAdmin")
                        .WithMany()
                        .HasForeignKey("ReviewedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Appointment");

                    b.Navigation("Client");

                    b.Navigation("Expert");

                    b.Navigation("ReviewedByAdmin");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.Expert", b =>
                {
                    b.Navigation("ExpertCertificates");

                    b.Navigation("ExpertSpecializations");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.ExpertScheduleTemplate", b =>
                {
                    b.Navigation("TimeSlots");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.ServicePackage", b =>
                {
                    b.Navigation("ClientPackages");
                });

            modelBuilder.Entity("HealthLink.Api.Entities.Specialization", b =>
                {
                    b.Navigation("ExpertSpecializations");
                });
#pragma warning restore 612, 618
        }
    }
}
