'use client';

import { useState, useEffect } from 'react';
import {
    Box,
    Typography,
    Paper,
    IconButton,
    Select,
    MenuItem,
    FormControl,
    Button,
    Stack,
    Divider
} from '@mui/material';
import ChevronLeftIcon from '@mui/icons-material/ChevronLeft';
import ChevronRightIcon from '@mui/icons-material/ChevronRight';

const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5107';

interface Props {
    onError: (message: string) => void;
    onSuccess: (message: string) => void;
}

enum SlotStatus {
    Available = 0,
    Booked = 1,
    Closed = 2
}

interface TimeSlot {
    time: string;
    status: SlotStatus;
    isAutoGenerated?: boolean;
}

export default function CalendarView({ onError, onSuccess }: Props) {
    const [currentDate, setCurrentDate] = useState(new Date());
    const [selectedDate, setSelectedDate] = useState<Date>(new Date());
    const [timeSlots, setTimeSlots] = useState<TimeSlot[]>([]);
    const [loading, setLoading] = useState(false);

    // Generate time slots from 00:00 to 23:30 in 30-minute intervals
    const generateTimeSlots = (): TimeSlot[] => {
        const slots: TimeSlot[] = [];
        for (let hour = 0; hour < 24; hour++) {
            for (let minute = 0; minute < 60; minute += 30) {
                const time = `${hour.toString().padStart(2, '0')}:${minute.toString().padStart(2, '0')}`;
                slots.push({ time, status: SlotStatus.Closed, isAutoGenerated: false });
            }
        }
        return slots;
    };

    const fetchAvailability = async (date: Date) => {
        try {
            setLoading(true);
            const year = date.getFullYear();
            const month = (date.getMonth() + 1).toString().padStart(2, '0');
            const day = date.getDate().toString().padStart(2, '0');
            const dateStr = `${year}-${month}-${day}`;

            const response = await fetch(`${API_URL}/api/expert/availability/daily?date=${dateStr}`, {
                headers: {
                    'Authorization': `Bearer ${localStorage.getItem('accessToken')}`
                }
            });

            if (!response.ok) {
                if (response.status === 401) {
                    onError('Oturum süreniz dolmuş. Lütfen tekrar giriş yapın.');
                    return;
                }
                throw new Error('Müsaitlik bilgisi alınamadı');
            }

            const availabilitySlots = await response.json();

            // Convert API response directly to time slots - no fixed slot generation
            const updatedSlots: TimeSlot[] = availabilitySlots.map((apiSlot: any) => {
                const slotTime = new Date(apiSlot.startDateTime);
                const time = `${slotTime.getHours().toString().padStart(2, '0')}:${slotTime.getMinutes().toString().padStart(2, '0')}`;

                return {
                    time,
                    status: apiSlot.status as SlotStatus,
                    isAutoGenerated: apiSlot.isAutoGenerated || false
                };
            });

            setTimeSlots(updatedSlots);
        } catch (err) {
            onError(err instanceof Error ? err.message : 'Bir hata oluştu');
            setTimeSlots([]);  // Empty array instead of generating closed slots
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchAvailability(selectedDate);
    }, [selectedDate]);

    const getDaysInMonth = (date: Date) => {
        const year = date.getFullYear();
        const month = date.getMonth();
        const firstDay = new Date(year, month, 1);
        const lastDay = new Date(year, month + 1, 0);
        const daysInMonth = lastDay.getDate();
        // Get day of week (0=Sunday, 1=Monday, etc.) and adjust for Monday start
        let startDayOfWeek = firstDay.getDay() - 1;
        if (startDayOfWeek === -1) startDayOfWeek = 6; // Sunday becomes last day

        const days: (Date | null)[] = [];

        // Add empty cells for days before month starts
        for (let i = 0; i < startDayOfWeek; i++) {
            days.push(null);
        }

        // Add all days in month
        for (let i = 1; i <= daysInMonth; i++) {
            days.push(new Date(year, month, i));
        }

        return days;
    };

    const handlePreviousMonth = () => {
        const newDate = new Date(currentDate);
        newDate.setMonth(newDate.getMonth() - 1);
        setCurrentDate(newDate);
    };

    const handleNextMonth = () => {
        const newDate = new Date(currentDate);
        newDate.setMonth(newDate.getMonth() + 1);
        setCurrentDate(newDate);
    };

    const handleMonthChange = (event: any) => {
        const [year, month] = event.target.value.split('-');
        setCurrentDate(new Date(parseInt(year), parseInt(month), 1));
    };

    const getMonthYearValue = (date: Date) => {
        return `${date.getFullYear()}-${date.getMonth()}`;
    };

    const isToday = (date: Date | null) => {
        if (!date) return false;
        const today = new Date();
        return date.toDateString() === today.toDateString();
    };

    const isSelected = (date: Date | null) => {
        if (!date) return false;
        return date.toDateString() === selectedDate.toDateString();
    };

    const handleDateClick = (date: Date | null) => {
        if (date) {
            setSelectedDate(date);
        }
    };

    const toggleTimeSlot = (index: number) => {
        setTimeSlots(prev => prev.map((slot, i) => {
            if (i !== index) return slot;

            // Don't allow changing booked slots
            if (slot.status === SlotStatus.Booked) return slot;

            // Cycle: Closed -> Available -> Closed
            const newStatus = slot.status === SlotStatus.Closed
                ? SlotStatus.Available
                : SlotStatus.Closed;

            return { ...slot, status: newStatus };
        }));
    };

    const handleSaveSlots = () => {
        // TODO: Save to backend
        onSuccess('Saat aralıkları kaydedildi');
    };

    const DAY_NAMES = ['P', 'S', 'Ç', 'P', 'C', 'C', 'P']; // Pzt, Sal, Çar, Per, Cum, Cmt, Paz
    const MONTHS = [
        'Ocak', 'Şubat', 'Mart', 'Nisan', 'Mayıs', 'Haziran',
        'Temmuz', 'Ağustos', 'Eylül', 'Ekim', 'Kasım', 'Aralık'
    ];

    // Generate month options for dropdown (current year ± 1 year)
    const getMonthOptions = () => {
        const options = [];
        const currentYear = new Date().getFullYear();
        for (let year = currentYear - 1; year <= currentYear + 1; year++) {
            for (let month = 0; month < 12; month++) {
                options.push({
                    value: `${year}-${month}`,
                    label: `${MONTHS[month]} ${year}`
                });
            }
        }
        return options;
    };

    return (
        <Box sx={{ p: 3 }}>
            <Typography variant="h5" gutterBottom fontWeight={600} sx={{ mb: 1 }}>
                Müsaitlik Takvimi
            </Typography>
            <Typography variant="body2" color="text.secondary" sx={{ mb: 4 }}>
                Bir güne tıklayarak o gün için müsait olduğunuz saatleri belirleyin
            </Typography>

            <Box sx={{ display: 'flex', gap: 3 }}>
                {/* Calendar Section */}
                <Box sx={{ flex: '0 0 65%' }}>
                    <Paper
                        elevation={0}
                        sx={{
                            p: 3,
                            border: 1,
                            borderColor: 'divider',
                            borderRadius: 2
                        }}
                    >
                        {/* Month Selector */}
                        <Box sx={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', mb: 3 }}>
                            <FormControl size="small" sx={{ minWidth: 180 }}>
                                <Select
                                    value={getMonthYearValue(currentDate)}
                                    onChange={handleMonthChange}
                                    sx={{
                                        fontWeight: 600,
                                        '& .MuiOutlinedInput-notchedOutline': { border: 'none' },
                                        '& .MuiSelect-select': { py: 0.5 }
                                    }}
                                >
                                    {getMonthOptions().map((option) => (
                                        <MenuItem key={option.value} value={option.value}>
                                            {option.label}
                                        </MenuItem>
                                    ))}
                                </Select>
                            </FormControl>

                            <Box>
                                <IconButton size="small" onClick={handlePreviousMonth}>
                                    <ChevronLeftIcon />
                                </IconButton>
                                <IconButton size="small" onClick={handleNextMonth}>
                                    <ChevronRightIcon />
                                </IconButton>
                            </Box>
                        </Box>

                        {/* Calendar Grid */}
                        <Box>
                            {/* Day Headers */}
                            <Box sx={{ display: 'flex', mb: 1 }}>
                                {DAY_NAMES.map((day, index) => (
                                    <Box
                                        key={`day-${index}`}
                                        sx={{ flex: 1, textAlign: 'center' }}
                                    >
                                        <Typography
                                            variant="caption"
                                            color="text.secondary"
                                            fontWeight={500}
                                        >
                                            {day}
                                        </Typography>
                                    </Box>
                                ))}
                            </Box>

                            {/* Calendar Days */}
                            <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.5 }}>
                                {getDaysInMonth(currentDate).map((date, index) => (
                                    <Box
                                        key={`date-${index}`}
                                        sx={{
                                            width: 'calc(14.28% - 4px)',
                                            display: 'flex',
                                            justifyContent: 'center',
                                            alignItems: 'center'
                                        }}
                                    >
                                        {date ? (
                                            <Box
                                                onClick={() => handleDateClick(date)}
                                                sx={{
                                                    width: 50,
                                                    height: 50,
                                                    display: 'flex',
                                                    alignItems: 'center',
                                                    justifyContent: 'center',
                                                    borderRadius: '50%',
                                                    cursor: 'pointer',
                                                    bgcolor: isToday(date)
                                                        ? 'primary.main'
                                                        : isSelected(date)
                                                            ? 'primary.light'
                                                            : 'transparent',
                                                    color: isToday(date)
                                                        ? 'white'
                                                        : isSelected(date)
                                                            ? 'primary.main'
                                                            : 'text.primary',
                                                    fontWeight: isToday(date) || isSelected(date) ? 600 : 400,
                                                    border: isSelected(date) && !isToday(date) ? 2 : 0,
                                                    borderColor: 'primary.main',
                                                    transition: 'all 0.2s',
                                                    '&:hover': {
                                                        bgcolor: isToday(date)
                                                            ? 'primary.dark'
                                                            : 'action.hover',
                                                        transform: 'scale(1.05)'
                                                    }
                                                }}
                                            >
                                                <Typography variant="body2">
                                                    {date.getDate()}
                                                </Typography>
                                            </Box>
                                        ) : (
                                            <Box sx={{ width: 50, height: 50 }} />
                                        )}
                                    </Box>
                                ))}
                            </Box>
                        </Box>
                    </Paper>
                </Box>

                {/* Time Slots Panel - Always Visible */}
                <Box sx={{ flex: '0 0 35%' }}>
                    <Paper
                        elevation={0}
                        sx={{
                            p: 3,
                            border: 1,
                            borderColor: 'divider',
                            borderRadius: 2,
                            height: '100%',
                            display: 'flex',
                            flexDirection: 'column'
                        }}
                    >
                        <Typography variant="h6" fontWeight={600} sx={{ mb: 1 }}>
                            {selectedDate.toLocaleDateString('tr-TR', {
                                day: 'numeric',
                                month: 'long',
                                year: 'numeric'
                            })}
                        </Typography>

                        <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
                            Müsait olduğunuz saat aralıklarını seçin
                        </Typography>

                        <Divider sx={{ mb: 2 }} />

                        <Box sx={{
                            display: 'grid',
                            gridTemplateColumns: 'repeat(4, 1fr)',
                            gap: 0.75,
                            maxHeight: 450,
                            overflow: 'auto',
                            pr: 0.5
                        }}>
                            {timeSlots.map((slot, index) => {
                                const isAvailable = slot.status === SlotStatus.Available;
                                const isBooked = slot.status === SlotStatus.Booked;
                                const isClosed = slot.status === SlotStatus.Closed;

                                return (
                                    <Box
                                        key={index}
                                        onClick={() => toggleTimeSlot(index)}
                                        sx={{
                                            p: 0.75,
                                            borderRadius: 1,
                                            border: 1,
                                            borderColor: isAvailable ? 'success.main' : isBooked ? 'error.main' : 'divider',
                                            bgcolor: isAvailable
                                                ? (slot.isAutoGenerated ? 'success.50' : 'success.100')
                                                : isBooked
                                                    ? 'error.50'
                                                    : 'grey.100',
                                            cursor: isBooked ? 'not-allowed' : 'pointer',
                                            textAlign: 'center',
                                            transition: 'all 0.2s',
                                            display: 'flex',
                                            flexDirection: 'column',
                                            alignItems: 'center',
                                            justifyContent: 'center',
                                            minHeight: 42,
                                            position: 'relative',
                                            opacity: isBooked ? 0.7 : 1,
                                            '&:hover': {
                                                bgcolor: isBooked
                                                    ? 'error.50'
                                                    : isAvailable
                                                        ? 'success.200'
                                                        : 'grey.200',
                                                transform: isBooked ? 'none' : 'scale(1.02)',
                                                boxShadow: isBooked ? 0 : 1
                                            }
                                        }}
                                    >
                                        {slot.isAutoGenerated && isAvailable && (
                                            <Box
                                                sx={{
                                                    position: 'absolute',
                                                    top: 2,
                                                    right: 2,
                                                    bgcolor: 'info.main',
                                                    color: 'white',
                                                    px: 0.5,
                                                    py: 0.25,
                                                    borderRadius: 0.5,
                                                    fontSize: '0.55rem',
                                                    fontWeight: 600
                                                }}
                                            >
                                                Auto
                                            </Box>
                                        )}
                                        <Typography
                                            variant="body2"
                                            fontWeight={isAvailable ? 600 : 400}
                                            sx={{ fontSize: '0.8rem', lineHeight: 1.2 }}
                                        >
                                            {slot.time}
                                        </Typography>
                                        <Typography
                                            variant="caption"
                                            color={isAvailable ? 'success.main' : isBooked ? 'error.main' : 'text.secondary'}
                                            sx={{ fontSize: '0.65rem', mt: 0.25 }}
                                        >
                                            {isAvailable ? '✓ Müsait' : isBooked ? '✗ Dolu' : '— Kapalı'}
                                        </Typography>
                                    </Box>
                                )
                            })}
                        </Box>

                        <Stack spacing={2} sx={{ mt: 3 }}>
                            <Button
                                variant="contained"
                                fullWidth
                                onClick={handleSaveSlots}
                            >
                                Kaydet
                            </Button>
                        </Stack>
                    </Paper>
                </Box>
            </Box>
        </Box>
    );
}
